### ISSUE TITLE
It doesn't bring the whole message

### ISSUE THREAD

**Issue by 0xfff0800** [devgauravjatt/free-tempmail-api#1]
I made an application but I had a problem when a long message is received it does not appear completely in json

[app iOS and android ](https://github.com/0xfff0800/Fake-Email-Flutter)

`{succuss: true, mails: [{@id: /messages/65705a8c5ced55f97d5bcda1, @type: Message, id: 65705a8c5ced55f97d5bcda1, msgid: <CAOWz6TTzGUgvJE1=MLUViuqQZC6YehN+jrmSH4K0XCqi-1jCWw@mail.gmail.com>, from: {address: email@gmail.com, name: FaLah Al Anazi}, to: [{address: kiran53795@wireconnected.com, name: }], subject: Fwd: Test, intro: 1. Trade-in values will vary based on the condition, year, and configuration of your eligible trade-in device. Not all devices…, seen: false, isDeleted: false, hasAttachments: false, size: 9509, downloadUrl: /messages/65705a8c5ced55f97d5bcda1/download, sourceUrl: /sources/65705a8c5ced55f97d5bcda1, createdAt: 2023-12-06T11:26:54+00:00, updatedAt: 2023-12-06T11:27:08+00:00, accountId: /accounts/65705a602925d353490a3dee}]}`

It only calls part of the message 👇

1. Trade-in values will vary based on the condition, year, and configuration of your eligible trade-in device. Not all devices…,

**Comment by sent** [comment]
Hello,

This is just a proxy service for the Mail.tm API which @devgauravjatt was not allowed to create. You can check it out here https://docs.mail.tm

Thanks!

**Comment by 0xfff0800** [comment]
Thank you so much for the clarification ! @sent 
We appreciate your efforts in providing this information
